ignoreWorkspaceRootCheck: true

packages:
  - ./
  - ./packages/*
  - ./playground
  - ./website
  - ./scripts/browser-fixture

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@octanejs/remix-router@0.1.49'
  - octane@0.3.2
  - '@octanejs/app-core@0.0.53'
  - '@octanejs/vite-plugin@0.1.57'
  - '@babel/generator@8.0.6'
  - '@babel/parser@8.0.6'
  - '@babel/traverse@8.0.6'
  - '@babel/types@8.0.6'
  - '@tsrx/prettier-plugin@0.4.6'
  - vite@8.3.0

patchedDependencies:
  "@octanejs/remix-router@0.1.49": patches/@octanejs__remix-router@0.1.49.patch
